import { navbar } from "vuepress-theme-hope";

export default navbar([
  "/",
  "/demo/",
  {
    text: "博文",
    icon: "pen-to-square",
    prefix: "/posts/",
    children: [
      {
        text: "Javascript面试题",
        icon: "pen-to-square",
        prefix: "javascript/",
        children: [
          {link:"data_type",text: "1、说说JavaScript中的数据类型？存储上的差别？"},
          {link:"array_api",text: "2、数组的常用方法有哪些？"},
          {link:"string_api",text: "3、JavaScript字符串的常用方法有哪些？"},
          {link:"type_conversion",text: "4、谈谈 JavaScript 中的类型转换机制"},
          {link:"== _===",text: "5、== 和 ===区别，分别在什么情况使用"},
          {link:"copy",text: "6、深拷贝浅拷贝的区别？如何实现一个深拷贝？"},
          {link:"closure",text: "7、说说你对闭包的理解？闭包使用场景"},
          {link:"scope",text: "8、说说你对作用域链的理解"},
          {link:"prototype",text: "9、JavaScript原型，原型链 ? 有什么特点？"},
          {link:"inherit",text: "10、Javascript如何实现继承？"},
          {link:"this",text: "11、谈谈this对象的理解"},
          {link:"context_stack",text: "12、JavaScript中执行上下文和执行栈是什么？"},
          {link:"event_Model",text: "13、说说JavaScript中的事件模型"},
          {link:"typeof_instanceof",text: "14、typeof 与 instanceof 区别"},
          {link:"event_agent",text: "15、解释下什么是事件代理？应用场景？"},
          {link:"new",text: "16、说说new操作符具体干了什么？"},
          {link:"ajax",text: "17、ajax原理是什么？如何实现？"},
          {link:"bind_call_apply",text: "18、bind、call、apply 区别？如何实现一个bind?"},
          {link:"regexp",text: "19、说说你对正则表达式的理解？应用场景？"},
          {link:"event_loop",text: "20、说说你对事件循环的理解"},
          {link:"Dom",text: "21、DOM常见的操作有哪些？"},
          {link:"BOM",text: "22、说说你对BOM的理解，常见的BOM对象你了解哪些？"},
          {link:"tail_recursion",text: "23、举例说明你对尾递归的理解，有哪些应用场景"},
          {link:"memory_leak",text: "24、说说 JavaScript 中内存泄漏的几种情况？"},
          {link:"cache",text: "25、Javascript本地存储的方式有哪些？区别及应用场景？"},
          {link:"functional_programming",text: "26、说说你对函数式编程的理解？优缺点？"},
          {link:"function_cache",text: "27、Javascript中如何实现函数缓存？函数缓存有哪些应用场景？"},
          {link:"loss_accuracy",text: "28、说说 Javascript 数字精度丢失的问题，如何解决？"},
          {link:"debounce_throttle",text: "29、什么是防抖和节流？有什么区别？如何实现？"},
          {link:"visible",text: "30、如何判断一个元素是否在可视区域中？"},
          {link:"continue_to_upload",text: "31、大文件上传如何做断点续传？"},
          {link:"pull_up_loading_pull_down_refresh",text: "32、如何实现上拉加载，下拉刷新？"},
          {link:"single_sign",text: "33、什么是单点登录？如何实现？"},
          {link:"security",text: "34、web常见的攻击方式有哪些？如何防御？"},
        ],
      },
      {
        text: "香蕉",
        icon: "pen-to-square",
        prefix: "banana/",
        children: [
          {
            text: "香蕉 11",
            icon: "pen-to-square",
            link: "1",
          },
          {
            text: "香蕉 2",
            icon: "pen-to-square",
            link: "2",
          },
          "3",
          "4",
        ],
      },
      { text: "樱桃", icon: "pen-to-square", link: "cherry" },
      { text: "火龙果", icon: "pen-to-square", link: "dragonfruit" },
      "tomato",
      "strawberry",
    ],
  },
  {
    text: "V2 文档",
    icon: "book",
    link: "https://theme-hope.vuejs.press/zh/",
  },
]);
