import { navbar } from "vuepress-theme-hope";

export default navbar([
  "/",
  // "/demo/",
  {
    text: "博文",
    icon: "pen-to-square",
    prefix: "/posts/",
    children: [
      {
        text: "Javascript系列",
        icon: "pen-to-square",
        prefix: "javascript/",
        children: [
          {link:"data_type",text: "1、说说JavaScript中的数据类型？存储上的差别？"},
          {link:"array_api",text: "2、数组的常用方法有哪些？"},
          {link:"string_api",text: "3、JavaScript字符串的常用方法有哪些？"},
          {link:"type_conversion",text: "4、谈谈 JavaScript 中的类型转换机制"},
          {link:"== _===",text: "5、== 和 ===区别，分别在什么情况使用"},
          {link:"copy",text: "6、深拷贝浅拷贝的区别？如何实现一个深拷贝？"},
          {link:"closure",text: "7、说说你对闭包的理解？闭包使用场景"},
          {link:"scope",text: "8、说说你对作用域链的理解"},
          {link:"prototype",text: "9、JavaScript原型，原型链 ? 有什么特点？"},
          {link:"inherit",text: "10、Javascript如何实现继承？"},
          {link:"this",text: "11、谈谈this对象的理解"},
          {link:"context_stack",text: "12、JavaScript中执行上下文和执行栈是什么？"},
          {link:"event_Model",text: "13、说说JavaScript中的事件模型"},
          {link:"typeof_instanceof",text: "14、typeof 与 instanceof 区别"},
          {link:"event_agent",text: "15、解释下什么是事件代理？应用场景？"},
          {link:"new",text: "16、说说new操作符具体干了什么？"},
          {link:"ajax",text: "17、ajax原理是什么？如何实现？"},
          {link:"bind_call_apply",text: "18、bind、call、apply 区别？如何实现一个bind?"},
          {link:"regexp",text: "19、说说你对正则表达式的理解？应用场景？"},
          {link:"event_loop",text: "20、说说你对事件循环的理解"},
          {link:"Dom",text: "21、DOM常见的操作有哪些？"},
          {link:"BOM",text: "22、说说你对BOM的理解，常见的BOM对象你了解哪些？"},
          {link:"tail_recursion",text: "23、举例说明你对尾递归的理解，有哪些应用场景"},
          {link:"memory_leak",text: "24、说说 JavaScript 中内存泄漏的几种情况？"},
          {link:"cache",text: "25、Javascript本地存储的方式有哪些？区别及应用场景？"},
          {link:"functional_programming",text: "26、说说你对函数式编程的理解？优缺点？"},
          {link:"function_cache",text: "27、Javascript中如何实现函数缓存？函数缓存有哪些应用场景？"},
          {link:"loss_accuracy",text: "28、说说 Javascript 数字精度丢失的问题，如何解决？"},
          {link:"debounce_throttle",text: "29、什么是防抖和节流？有什么区别？如何实现？"},
          {link:"visible",text: "30、如何判断一个元素是否在可视区域中？"},
          {link:"continue_to_upload",text: "31、大文件上传如何做断点续传？"},
          {link:"pull_up_loading_pull_down_refresh",text: "32、如何实现上拉加载，下拉刷新？"},
          {link:"single_sign",text: "33、什么是单点登录？如何实现？"},
          {link:"security",text: "34、web常见的攻击方式有哪些？如何防御？"},
        ]
      },
      {
        text: "Vue面试题",
        icon: "pen-to-square",
        prefix: "vue/",
        children: [
          {link:"vue",text: "说说你对vue的理解?"},
          {link:"spa",text: "说说你对SPA（单页应用）的理解?"},
          {link:"show_if",text: "Vue中的v-show和v-if怎么理解？"},
          {link:"new_vue",text: "Vue实例挂载的过程中发生了什么?"},
          {link:"lifecycle",text: "说说你对Vue生命周期的理解?"},
          {link:"if_for",text: "为什么Vue中的v-if和v-for不建议一起用?"},
          {link:"first_page_time",text: "SPA（单页应用）首屏加载速度慢怎么解决？"},
          {link:"data",text: "为什么data属性是一个函数而不是一个对象？"},
          {link:"data_object_add_attrs",text: "Vue中给对象添加新属性界面不刷新?"},
          {link:"components_plugin",text: "Vue中组件和插件有什么区别？"},
          {link:"communication",text: "Vue组件间通信方式都有哪些?"},
          {link:"bind",text: "说说你对双向绑定的理解?"},
          {link:"nexttick",text: "说说你对nexttick的理解?"},
          {link:"mixin",text: "说说你对vue的mixin的理解，有什么应用场景？"},
          {link:"slot",text: "说说你对slot的理解？slot使用场景有哪些？"},
          {link:"observable",text: "Vue.observable你有了解过吗？说说看"},
          {link:"key",text: "你知道vue中key的原理吗？说说你对它的理解？"},
          {link:"keepalive",text: "怎么缓存当前的组件？缓存后怎么更新？说说你对keep-alive的理解是什么？"},
          {link:"modifier",text: "Vue常用的修饰符有哪些？有什么应用场景？"},
          {link:"directive",text: "你有写过自定义指令吗？自定义指令的应用场景有哪些？"},
          {link:"filter",text: "Vue中的过滤器了解吗？过滤器的应用场景有哪些？"},
          {link:"vnode",text: "什么是虚拟DOM？如何实现一个虚拟DOM？说说你的思路"},
          {link:"diff",text: "你了解vue的diff算法吗？说说看"},
          {link:"axios",text: "Vue项目中有封装过axios吗？主要是封装哪方面的？"},
          {link:"axiosCode",text: "你了解axios的原理吗？有看过它的源码吗？"},
          {link:"ssr",text: "SSR解决了什么问题？有做过SSR吗？你是怎么做的？"},
          {link:"structure",text: "说下你的vue项目的目录结构，如果是大型项目你该怎么划分结构和划分组件呢？"},
          {link:"permission",text: "vue要做权限管理该怎么做？如果控制到按钮级别的权限怎么做？"},
          {link:"cors",text: "Vue项目中你是如何解决跨域的呢？"},
          {link:"404",text: "vue项目本地开发完成后部署到服务器后报404是什么原因呢？"},
          {link:"error",text: "你是怎么处理vue项目中的错误的？"},
          {link:"vue3_vue2", text: "Vue3有了解过吗？能说说跟Vue2的区别吗？" }
        ]
      },
      {
        text: "Vue3系列",
        icon: "pen-to-square",
        prefix: "vue3/",
        children: [
          {link:"goal", text: "Vue3.0的设计目标是什么？做了哪些优化?"},
          {link:"performance", text: "Vue3.0 性能提升主要是通过哪几方面体现的？"},
          {link:"proxy",text:  "Vue3.0里为什么要用 Proxy API 替代 defineProperty API ？"},
          {link:"composition", text: "Vue3.0 所采用的 Composition Api 与 Vue2.x 使用的 Options Api 有什么不同？"},
          {link:"treeshaking",text:  "说说Vue 3.0中Treeshaking特性？举例说明一下？"},
          {link:"modal_component", text: "用Vue3.0 写过组件吗？如果想实现一个 Modal你会怎么设计？"},
        ],
      },
     {
        text: "ES6系列",
        icon: "pen-to-square",
        prefix: "es6/",
        children: [
          {link:"var_let_const", text: "说说var、let、const之间的区别"},
          {link:"array", text: "ES6中数组新增了哪些扩展?"},
          {link:"object", text: "ES6中对象新增了哪些扩展?"},
          {link:"function", text: "ES6中函数新增了哪些扩展?"},
          {link:"set_map",text:  "ES6中新增的Set、Map两种数据结构怎么理解?"},
          {link:"promise",text:  "你是怎么理解ES6中 Promise的？使用场景？"},
          {link:"generator",text:  "怎么理解ES6中 Generator的？使用场景？"},
          {link:"proxy",text:  "你是怎么理解ES6中Proxy的？使用场景?"},
          {link:"module",text:  "你是怎么理解ES6中Module的？使用场景？"},
          {link:"decorator",text:  "你是怎么理解ES6中 Decorator 的？使用场景？"},
        ],
      },
      {
         text: "CSS系列",
        icon: "pen-to-square",
        prefix: "css/",
        children: [
          {link:"box",text:  "说说你对盒子模型的理解？"},
          {link:"selector", text: "css选择器有哪些？优先级？哪些属性可以继承？" },
          {link:"em_px_rem_vh_vw",text:  "说说em/px/rem/vh/vw区别？"},
          {link:"dp_px_dpr_ppi",text:  "说说设备像素、css像素、设备独立像素、dpr、ppi 之间的区别？"},
          {link:"hide_attributes",text:  "css中，有哪些方式可以隐藏页面元素？区别？"},
          {link:"BFC",text:  "谈谈你对BFC的理解？"},
          {link:"center",text:  "元素水平垂直居中的方法有哪些？如果元素不定宽高呢？"},
          {link:"column_layout",text:  "如何实现两栏布局，右侧自适应？三栏布局中间自适应呢？"},
          {link:"flexbox",text:  "说说flexbox（弹性盒布局模型）,以及适用场景？"},
          {link:"grid",text:  "介绍一下grid网格布局"},
          {link:"css3_features",text:  "CSS3新增了哪些新特性？"},
          {link:"animation",text:  "css3动画有哪些？"},
          {link:"layout_painting",text:  "怎么理解回流跟重绘？什么场景下会触发？"},
          {link:"responsive_layout",text:  "什么是响应式设计？响应式设计的基本原理是什么？如何做？"},
          {link:"css_performance",text:  "如果要做优化，CSS提高性能的方法有哪些？"},
          {link:"single_multi_line",text:  "如何实现单行／多行文本溢出的省略样式？"},
          {link:"visual_scrolling",text:  "如何使用css完成视差滚动效果？"},
          {link:"triangle",text:  "CSS如何画一个三角形？原理是什么？"},
          {link:"less_12px",text:  "让Chrome支持小于12px 的文字方式有哪些？区别？"},
          {link:"sass_less_stylus",text:  "说说对Css预编语言的理解？有哪些区别？"},
        ],
      },
      {
        text: "React系列",
        icon: "pen-to-square",
        prefix: "React/",
        children:[
          {link:"React",text:  "说说对React的理解？有哪些特性？"},
          {link:"Real DOM_Virtual DOM",text:  "说说 Real DOM和 Virtual DOM 的区别？优缺点？"},
          {link:"life cycle",text:  "说说 React 生命周期有哪些不同阶段？每个阶段对应的方法是？"},
          {link:"state_props",text:  "state 和 props有什么区别？"},
          {link:"super()_super(props)",text:  "super()和super(props)有什么区别？"},
          {link:"setState",text:  "说说 React中的setState执行机制"},
          {link:"SyntheticEvent",text:  "说说React的事件机制？"},
          {link:"Binding events",text:  "React事件绑定的方式有哪些？区别？"},
          {link:"Building components",text:  "React构建组件的方式有哪些？区别？"},
          {link:"communication",text:  "React中组件之间如何通信？"},
          {link:"key",text:  "React中的key有什么作用？"},
          {link:"React refs",text:  "说说对React refs 的理解？应用场景？"},
          {link:"class_function component",text:  "说说对React中类组件和函数组件的理解？有什么区别？"},
          {link:"controlled_Uncontrolled",text:  "说说对受控组件和非受控组件的理解？应用场景？"},
          {link:"High order components",text:  "说说对高阶组件的理解？应用场景？"},
          {link:"React Hooks",text:  "说说对React Hooks的理解？解决了什么问题？"},
          {link:"import css",text:  "说说react中引入css的方式有哪几种？区别？"},
          {link:"animation",text:  "在react中组件间过渡动画如何实现？"},
          {link:"redux",text:  "说说你对Redux的理解？其工作原理？"},
          {link:"Redux Middleware",text:  "说说对Redux中间件的理解？常用的中间件有哪些？实现原理？"},
          {link:"how to use redux",text:  "你在React项目中是如何使用Redux的? 项目结构是如何划分的？"},
          {link:"React Router",text:  "说说你对React Router的理解？常用的Router组件有哪些？"},
          {link:"React Router model",text:  "说说React Router有几种模式？实现原理？？"},
          {link:"immutable",text:  "说说你对immutable的理解？如何应用在react项目中？"},
          {link:"render",text:  "说说React render方法的原理？在什么时候会被触发？"},
          {link:"improve_render",text:  "说说你是如何提高组件的渲染效率的？在React中如何避免不必要的render？"},
          {link:"diff",text:  "说说React diff的原理是什么？"},
          {link:"Fiber",text:  "说说对Fiber架构的理解？解决了什么问题？"},
          {link:"JSX to DOM",text:  "说说React Jsx转换成真实DOM过程？"},
          {link:"Improve performance",text:  "说说 React 性能优化的手段有哪些？"},
          {link:"capture error",text:  "说说你在React项目是如何捕获错误的？"},
          {link:"server side rendering",text:  "说说React服务端渲染怎么做？原理是什么？"},
          {link:"summary", text: "说说你在使用React 过程中遇到的常见问题？如何解决?" }
        ]
      },
      {
         text: "TypeScript系列",
        icon: "pen-to-square",
        prefix: "typescript/",
        children:[
          {link:"typescript_javascript",text:  "说说你对 TypeScript 的理解？与 JavaScript 的区别？"},
          {link:"data_type",text:  "说说 typescript 的数据类型有哪些？"},
          {link:"enum",text:  "说说你对 TypeScript 中枚举类型的理解？应用场景？"},
          {link:"interface",text:  "说说你对 TypeScript 中接口的理解？应用场景？"},
          {link:"class",text:  "说说你对 TypeScript 中类的理解？应用场景？"},
          {link:"function",text:  "说说你对 TypeScript 中函数的理解？与 JavaScript 函数的区别？"},
          {link:"generic",text:  "说说你对 TypeScript 中泛型的理解？应用场景？"},
          {link:"high type",text:  "说说你对 TypeScript 中高级类型的理解？有哪些？"},
          {link:"decorator",text:  "说说你对 TypeScript 装饰器的理解？应用场景？"},
          {link:"namespace_module",text:  "说说对 TypeScript 中命名空间与模块的理解？区别？"},
          {link:"react",text:  "说说如何在 React 项目中应用 TypeScript？"},
          {link:"vue", text: "说说如何在Vue项目中应用TypeScript？" }
        ]
      },
      {
             text: "Webpack系列",
        icon: "pen-to-square",
        prefix: "webpack/",
        children:[
          {link:"webpack", text: "说说你对webpack的理解？解决了什么问题？"},
          {link:"build_process", text: "说说webpack的构建流程?"},
          {link:"Loader", text: "说说webpack中常见的Loader？解决了什么问题？"},
          {link:"Plugin", text: "说说webpack中常见的Plugin？解决了什么问题？"},
          {link:"Loader_Plugin", text: "说说Loader和Plugin的区别？编写Loader，Plugin的思路？"},
          {link:"HMR", text: "说说webpack的热更新是如何做到的？原理是什么？"},
          {link:"proxy", text: "说说webpack proxy工作原理？为什么能解决跨域?"},
          {link:"performance", text: "说说如何借助webpack来优化前端性能？"},
          {link:"improve_build", text: "如何提高webpack的构建速度？"},
          {link:"Rollup_Parcel_snowpack_Vite", text: "与webpack类似的工具还有哪些？区别？"},
        ]
      },
          {
           text: "HTTP系列",
        icon: "pen-to-square",
        prefix: "http/",
        children:[
          {link:"HTTP_HTTPS", text: "什么是HTTP? HTTP 和 HTTPS 的区别?"},
          {link:"HTTPS", text: "为什么说HTTPS比HTTP安全? HTTPS是如何保证安全的？"},
          {link:"UDP_TCP", text: "如何理解UDP 和 TCP? 区别? 应用场景?"},
          {link:"OSI", text: "如何理解OSI七层模型?"},
          {link:"TCP_IP", text: "如何理解TCP/IP协议?"},
          {link:"DNS", text: "DNS协议 是什么？说说DNS 完整的查询过程?"},
          {link:"CDN", text: "如何理解CDN？说说实现原理？"},
          {link:"1.0_1.1_2.0", text: "说说 HTTP1.0/1.1/2.0 的区别?"},
          {link:"status", text: "说说 HTTP 常见的状态码有哪些，适用场景？"},
          {link:"GET_POST", text: "说一下 GET 和 POST 的区别？"},
          {link:"headers", text: "说说 HTTP 常见的请求头有哪些? 作用？"},
          {link:"after_url", text: "说说地址栏输入 URL 敲下回车后发生了什么？"},
          {link:"handshakes_waves", text: "说说TCP为什么需要三次握手和四次挥手？"},
          {link:"WebSocket", text: "说说对WebSocket的理解？应用场景？" }
        ]
      },
           {
         text: "NodeJS系列",
        icon: "pen-to-square",
        prefix: "NodeJS/",
        children:[
          {link:"nodejs", text: "说说你对 Node.js 的理解？优缺点？应用场景？"},
          {link:"global", text: "说说 Node.js 有哪些全局对象？"},
          {link:"process", text: "说说对 Node 中的 process 的理解？有哪些常用方法？"},
          {link:"fs", text: "说说对 Node 中的 fs模块的理解? 有哪些常用方法"},
          {link:"Buffer", text: "说说对 Node 中的 Buffer 的理解？应用场景？"},
          {link:"Stream", text: "说说对 Node 中的 Stream 的理解？应用场景？"},
          {link:"EventEmitter", text: "说说Node中的EventEmitter? 如何实现一个EventEmitter?"},
          {link:"event_loop", text: "说说对 Nodejs 中的事件循环机制理解?"},
          {link:"require_order", text: "说说 Node 文件查找的优先级以及 Require 方法的文件查找策略?"},
          {link:"middleware", text: "说说对中间件概念的理解，如何封装 node 中间件？"},
          {link:"jwt", text: "如何实现jwt鉴权机制？说说你的思路"},
          {link:"file_upload", text: "如何实现文件上传？说说你的思路"},
          {link:"paging", text: "如果让你来设计一个分页功能, 你会怎么设计? 前后端如何交互?"},
          {link:"performance", text: "Node性能如何进行监控以及优化？"},
        ]
      },
      {
              text: "GIT版本控制系列",
        icon: "pen-to-square",
        prefix: "git/",
        children:[
          {link:"Version control", text: "说说你对版本管理的理解？常用的版本管理工具有哪些？"},
          {link:"Git", text: "说说你对Git的理解？"},
          {link:"fork_clone_branch", text: "说说Git中 fork, clone,branch这三个概念，有什么区别?"},
          {link:"command", text: "说说Git常用的命令有哪些？"},
          {link:"HEAD_tree_index", text: "说说Git 中 HEAD、工作树和索引之间的区别？"},
          {link:"git pull _git fetch", text: "说说对git pull 和 git fetch 的理解？有什么区别？"},
          {link:"git stash", text: "说说你对git stash 的理解？应用场景？"},
          {link:"git rebase_ git merge", text: "说说你对git rebase 和 git merge的理解？区别？"},
          {link:"conflict", text: "说说 git 发生冲突的场景？如何解决？"},
          {link:"git reset_ git revert", text: "说说你对git reset 和 git revert 的理解？区别？"},
        ]
      },
      {
          text: "操作系统系列",
        icon: "pen-to-square",
        prefix: "linux/",
        children:[
           {link:"linux", text: "说说你对操作系统的理解？核心概念有哪些？"},
           {link:"thread_process", text: "说说什么是进程？什么是线程？区别？"},
           {link:"file", text: "说说 linux系统下 文件操作常用的命令有哪些？"},
           {link:"vim", text: "说说 linux 系统下 文本编辑常用的命令有哪些？"},
           {link:"linux users", text: "说说你对 linux 用户管理的理解？相关的命令有哪些？"},
           {link:"redirect_pipe", text: "说说你对输入输出重定向和管道的理解？应用场景？"},
           {link:"shell", text: "说说你对 shell 的理解？常见的命令？"},
        ]
      },
       {
        text: "算法与数据结构系列",
        icon: "pen-to-square",
        prefix: "algorithm/",
        children:[
           {link:"Algorithm", text: "说说你对算法的理解？应用场景？"},
           {link:"time_space", text: "说说你对算法中时间复杂度，空间复杂度的理解？如何计算？"},
           {link:"structure", text: "说说你对数据结构的理解？有哪些？区别？"},
           {link:"stack_queue", text: "说说你对栈、队列的理解？应用场景？"},
           {link:"Linked List", text: "说说你对链表的理解？常见的操作有哪些？"},
           {link:"set", text: "说说你对集合的理解？常见的操作有哪些？"},
           {link:"tree", text: "说说你对树的理解？相关的操作有哪些？"},
           {link:"Heap", text: "说说你对堆的理解？如何实现？应用场景？"},
           {link:"graph", text: "说说你对图的理解？相关操作有哪些？"},
           {link:"sort", text: "说说常见的排序算法有哪些？区别？"},
           {link:"bubbleSort", text: "说说你对冒泡排序的理解？如何实现？应用场景？"},
           {link:"selectionSort", text: "说说你对选择排序的理解？如何实现？应用场景？"},
           {link:"insertionSort", text: "说说你对插入排序的理解？如何实现？应用场景？"},
           {link:"mergeSort", text: "说说你对归并排序的理解？如何实现？应用场景？"},
           {link:"quickSort", text: "说说你对快速排序的理解？如何实现？应用场景？"},
           {link:"BinarySearch", text: "说说你对二分查找的理解？如何实现？应用场景？"},
           {link:"design1", text: "说说说你对分而治之、动态规划的理解？区别？"},
           {link:"design2", text: "说说你对贪心算法、回溯算法的理解？应用场景？"},
        ]
      },
      {
         text: "小程序系列",
        icon: "pen-to-square",
        prefix: "applet/",
        children:[
           {link:"applet", text: "说说你对微信小程序的理解？优缺点？"},
           {link:"lifecycle", text: "说说微信小程序的生命周期函数有哪些？"},
           {link:"navigate", text: "说说微信小程序中路由跳转的方式有哪些？区别？"},
           {link:"optimization", text: "说说提高微信小程序的应用速度的手段有哪些？"},
           {link:"login", text: "说说微信小程序的登录流程？"},
           {link:"publish", text: "说说微信小程序的发布流程？"},
           {link:"requestPayment", text: "说说微信小程序的支付流程？"},
           {link:"WebView_jscore", text: "说说微信小程序的实现原理？"},
        ]
      },
      {
        text: "设计模式系列",
        icon: "pen-to-square",
        prefix: "design/",
        children:[
           {link:"design", text: "说说对设计模式的理解？常见的设计模式有哪些？"},
           {link:"Singleton Pattern", text: "说说你对单例模式的理解？如何实现？"},
           {link:"Factory  Pattern", text: "说说你对工厂模式的理解？应用场景？"},
           {link:"Strategy Pattern", text: "说说你对策略模式的理解？应用场景？"},
           {link:"Proxy Pattern", text: "说说你对代理模式的理解？应用场景？"},
           {link:"Observer  Pattern", text: "说说你对发布订阅、观察者模式的理解？区别？"},
        ]
      },
    ]
  },
  
  // {
  //   text: "V2 文档",
  //   icon: "book",
  //   link: "https://theme-hope.vuejs.press/zh/",
  // },
]);
